# Site settings
title: nico leffel
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nicoleffel.net" # the base hostname & protocol for your site, e.g. http://example.comxw
google_analytics: UA-34137671-1
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
